# Conversation states cho bot
(WAITING_PHONE, WAITING_CODE, WAITING_2FA_PASSWORD, WAITING_SOURCE_CHANNEL, WAITING_TARGET_CHANNEL,
 WAITING_EXTRACT_PATTERN, WAITING_HEADER, WAITING_FOOTER, 
 WAITING_BUTTON_TEXT, WAITING_BUTTON_URL) = range(10) 